CREATE SEQUENCE SQ_PERSON START WITH 1 INCREMENT BY 1 MAXVALUE 99999999999999;

CREATE SEQUENCE SQ_ADDRESS START WITH 1 INCREMENT BY 1 MAXVALUE 99999999999999;

CREATE TABLE IF NOT EXISTS PERSON (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SQ_PERSON'),
    NAME_PERSON VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS ADDRESS (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SQ_ADDRESS'),
    STREET VARCHAR(255) NOT NULL,
    ZIPCODE VARCHAR(10) NOT NULL,
    STREET_NUMBER VARCHAR(20) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    STATE_SHORTNAME VARCHAR(10) NOT NULL,
    PERSON_ID BIGINT NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
);